#         ___                            _        _    __  __
#       / __|     _ _    ___     ___    | |_     (_)   \ \/ /
#      | (_ |    | '_|  / -_)   / -_)   |  _|    | |    >  <
#       \___|   _|_|_   \___|   \___|   _\__|   _|_|_  /_/\_\
#    _|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|
#    "`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'

# cooldown: s(for seconds), mi(for minutes), m(for months), w(for weeks) and y(to years)
# types: repetitive (it repeats every certain time established by the cooldown [will produce SPAM]),
# on_join (it occurs when the player joins, it can have a cooldown)

messages:
  welcome_message:
    enabled: true
    type: on_join
    message:
      - "&cPlugin not configured!"
    cooldown: true # [False will produce an instant-message send]
    cooldown_time: 5s

  update_log:
    enabled: false
    type: repetitive
    message:
      - "&2ApePvP 0.4 has released!"
      - "&2Check the changelog to view changes!"
    cooldown: true # [False will make SPAM]
    cooldown_time: 15s

  spam:
    enabled: false
    type: repetitive
    message:
      - "&1Made by Enttbot"
    cooldown: true
    cooldown_time: 10s