main: x.Entt.GreetiX.GX
name: GreetiX
version: 1.1.0
description: Perform actions when a player joins.
authors:
  - Enttbot
api-version: "1.13"
softdepend: [PlaceholderAPI]

commands:
  greetix:
    description: Main command of GreetiX
    aliases:
      - gx

permissions:
  greetix.*:
    default: op
    description: All permissions for GreetiX
    children:
      greetix.commands: true
      greetix.updatelog: true
  greetix.commands:
    description: Permission to use /gx reload
    default: op
  greetix.updatelog:
    description: Get a message warning about a new update
    default: op