main: x.Entt.GreetiX.GX
name: GreetiX
version: 1.0.1
description: Do something when a player joins
authors: [Enttbot]
api-version: "1.13"

commands:
  greetix:
    description: Main cmd of GreetiX
    aliases:
      - gx

permissions:
  greetix.reload:
    description: The perm for use /gx reload
    default: op